<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

/**
 * Fix gold_rates table:
 * 1. Expand metal_type ENUM from ['22K'] to ['22K', '24K', 'Silver']
 * 2. Drop the UNIQUE constraint on (company_id, rate_date, metal_type)
 *    to allow multiple rate entries per day per metal type.
 */
class FixGoldRatesTable extends Migration
{
  public function up()
  {
    // 1. Fix the ENUM - was incorrectly only ['22K'], now includes all 3 values.
    //    Use ALTER TABLE directly since DBForge::modifyColumn has ENUM quirks.
    $this->db->query("ALTER TABLE `gold_rates` MODIFY COLUMN `metal_type` ENUM('22K','24K','Silver') NOT NULL");

    // 2. Drop the UNIQUE KEY that blocks multiple entries per day.
    //    The key name is auto-generated by CI4 forge as 'company_id_rate_date_metal_type'.
    //    We check if it exists first to make the migration safe to re-run.
    $this->db->query("
            ALTER TABLE `gold_rates`
            DROP INDEX IF EXISTS `company_id_rate_date_metal_type`
        ");
  }

  public function down()
  {
    // Restore narrow ENUM (for rollback only — not recommended in production)
    $this->db->query("ALTER TABLE `gold_rates` MODIFY COLUMN `metal_type` ENUM('22K') NOT NULL");

    // Re-add unique constraint
    $this->db->query("ALTER TABLE `gold_rates` ADD UNIQUE KEY `company_id_rate_date_metal_type` (`company_id`, `rate_date`, `metal_type`)");
  }
}
